### ISSUE TITLE
请问下博主有lab的参考吗，十分感谢

### ISSUE THREAD

**Issue by hypocrasy** [Gallium70/rCore-Tutorial-OsLab-2022Spring#1]

**Comment by Gallium70** [comment]
本项目已迁移至 [LearningOS/rCore-Tutorial-Code-2022S](https://github.com/LearningOS/rCore-Tutorial-Code-2022S) 继续开发。
lab 为课程作业的一部分，不会提供参考答案或实现，通过测例即可。后续如有任何问题可前往上述仓库发 issue 。
